---
- name: Create Prometheus system user
  user:
    name: prometheus
    shell: /bin/false
    system: yes
    create_home: no

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version }}/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: "0644"
### Obrisi posle tar i otpakovani tar
- name: Extract Prometheus tarball
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy binaries to /usr/local/bin
  copy:
    src: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy consoles and console_libraries
  copy:
    src: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes
  loop:
    - consoles
    - console_libraries

- name: Copy default prometheus.yml config
  copy:
    src: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64/prometheus.yml"
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
    remote_src: yes

- name: Create systemd unit file for Prometheus
  template:
    src: "templates/prometheus.service.j2"
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Remove Prometheus tarball
  file:
    path: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
    state: absent

- name: Remove extracted Prometheus directory
  file:
    path: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64"
    state: absent
